export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const CART_ADD_ITEM = 'CART_ADD_ITEM ';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM ';
export const CART_EMPTY = 'CART_EMPTY';
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const REMOVE_ADDRESS = 'REMOVE_ADDRESS';
export const PAYMENT_METHOD = 'PAYMENT_METHOD';
export const TOTAL_PRICE = 'TOTAL_PRICE';

export const ORDER_REQUEST = 'ORDER_REQUEST';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_FAIL = 'ORDER_FAIL';
export const ORDER_RESET = 'ORDER_RESET';

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

export const ADD_DELIVEY_ADDRESS = 'ADD_DELIVEY_ADDRESS';
export const REMOVE_DELIVEY_ADDRESS = 'REMOVE_DELIVEY_ADDRESS';
export const ORDER_DETAILS_REQUEST = ' ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = ' ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = ' ORDER_DETAILS_FAIL';

export const ORDER_MINE_LIST_REQUEST = ' ORDER_MINE_LIST_REQUEST';
export const ORDER_MINE_LIST_SUCCESS = ' ORDER_MINE_LIST_SUCCESS';
export const ORDER_MINE_LIST_FAIL = ' ORDER_MINE_LIST_FAIL';

export const FASHION_PRODUCT_CREATE_REQUEST = 'FASHION_PRODUCT_CREATE_REQUEST';
export const FASHION_PRODUCT_CREATE_SUCCESS = 'FASHION_PRODUCT_CREATE_SUCCESS';
export const FASHION_PRODUCT_CREATE_FAIL = 'FASHION_PRODUCT_CREATE_FAIL';
export const FASHION_PRODUCT_CREATE_RESET = 'FASHION_PRODUCT_CREATE_RESET';

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL';
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET';

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';
export const PRODUCT_DELETE_RESET = 'PRODUCT_DELETE_RESET';

export const ORDER_LIST_USER_REQUEST = 'ORDER_LIST_USER_REQUEST';
export const ORDER_LIST_USER_SUCCESS = 'ORDER_LIST_USER_SUCCESS';
export const ORDER_LIST_USER_FAIL = 'ORDER_LIST_USER_FAIL';
export const ORDER_LIST_USER_RESET = 'ORDER_LIST_USER_RESET';

export const USER_ORDER_DELETE_REQUEST = 'USER_ORDER_DELETE_REQUEST';
export const USER_ORDER_DELETE_SUCCESS = 'USER_ORDER_DELETE_SUCCESS';
export const USER_ORDER_DELETE_FAIL = 'USER_ORDER_DELETE_FAIL';
export const USER_ORDER_DELETE_RESET = 'USER_ORDER_DELETE_RESET';

export const ORDER_DELIVERED_REQUEST = 'ORDER_DELIVERED_REQUEST';
export const ORDER_DELIVERED_SUCCESS = 'ORDER_DELIVERED_SUCCESS';
export const ORDER_DELIVERED_FAIL = 'ORDER_DELIVERED_FAIL';
export const ORDER_DELIVERED_RESET = 'ORDER_DELIVERED_RESET';

export const ADD_CREATE_REQUEST = 'ADD_CREATE_REQUEST';
export const ADD_CREATE_SUCCESS = 'ADD_CREATE_SUCCESS';
export const ADD_CREATE_FAIL = 'ADD_CREATE_FAIL';
export const ADD_CREATE_RESET = 'ADD_CREATE_RESET';

export const CAROUSEL_FASHION_ADDS_REQUEST = 'CAROUSEL_FASHION_ADDS_REQUEST';
export const CAROUSEL_FASHION_ADDS_SUCCESS = 'CAROUSEL_FASHION_ADDS_SUCCESS';
export const CAROUSEL_FASHION_ADDS_FAIL = 'CAROUSEL_FASHION_ADDS_FAIL';

//Electronic Products

export const ELECTRONIC_ITEMS_LIST_REQUEST = 'ELECTRONIC_ITEMS_LIST_REQUEST';
export const ELECTRONIC_ITEMS_LIST_SUCCESS = 'ELECTRONIC_ITEMS_LIST_SUCCESS';
export const ELECTRONIC_ITEMS_LIST_FAIL = 'ELECTRONIC_ITEMS_LIST_FAIL';

export const ELECTRIC_PRODUCT_DETAILS_REQUEST =
	'ELECTRIC_PRODUCT_DETAILS_REQUEST';
export const ELECTRIC_PRODUCT_DETAILS_SUCCESS =
	'ELECTRIC_PRODUCT_DETAILS_SUCCESS';
export const ELECTRIC_PRODUCT_DETAILS_FAIL = 'ELECTRIC_PRODUCT_DETAILS_FAIL';

export const CAROUSEL_ELECTRIC_ADDS_REQUEST = 'CAROUSEL_ELECTRIC_ADDS_REQUEST';
export const CAROUSEL_ELECTRIC_ADDS_SUCCESS = 'CAROUSEL_ELECTRIC_ADDS_SUCCESS';
export const CAROUSEL_ELECTRIC_ADDS_FAIL = 'CAROUSEL_ELECTRIC_ADDS_FAIL';

export const ELECTRONICS_PRODUCT_CREATE_REQUEST =
	'ELECTRONICS_PRODUCT_CREATE_REQUEST';
export const ELECTRONICS_PRODUCT_CREATE_SUCCESS =
	'ELECTRONICS_PRODUCT_CREATE_SUCCESS';
export const ELECTRONICS_PRODUCT_CREATE_FAIL =
	'ELECTRONICS_PRODUCT_CREATE_FAIL';
export const ELECTRONICS_PRODUCT_CREATE_RESET =
	'ELECTRONICS_PRODUCT_CREATE_RESET';
